#This document generates NDC constraints for GCAM by taking in baseline emissions and baseline GDP
#and creating constratins consistent with the iNDCs based off these values. As GCAM currently has a base year
#of 2010 the reference case the iNDCs are based off of will be essentially a BAU without the NDCs as very
#little action had taken place by 2010. When GCAM moves its base year forward new considerations will need to be
#taken to alter this script. NOTE: GHG emissions price modifiers are based off of AR4
#JEH June 2019

#TO DO
#   Allow regions to specify their own demand adjuster (AR4, AR5, etc)
#   Decide what to do with conditional commitments
#   Alter values for indicative targets

#This version of the script uses AR4 to judge GHGs, but countries based their constraints off of several studies,
#so this could be updated to be region specific.

#!/usr/bin/env Rscript
#
# LEGAL NOTICE
# This computer software was prepared by Battelle Memorial Institute,
# hereinafter the Contractor, under Contract No. DE-AC05-76RL0 1830
# with the Department of Energy (DOE). NEITHER THE GOVERNMENT NOR THE
# CONTRACTOR MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY
# LIABILITY FOR THE USE OF THIS SOFTWARE. This notice including this
# sentence must appear on any copies of this computer software.
#
# EXPORT CONTROL
# User agrees that the Software will not be shipped, transferred or
# exported into any country or used in any manner prohibited by the
# United States Export Administration Act or any other applicable
# export laws, restrictions or regulations (collectively the "Export Laws").
# Export of the Software may require some form of license or other
# authority from the U.S. Government, and failure to obtain such
# export control license may result in criminal liability under
# U.S. laws. In addition, if the Software is identified as export controlled
# items under the Export Laws, User represents and warrants that User
# is not a citizen, or otherwise located within, an embargoed nation
# (including without limitation Iran, Syria, Sudan, Cuba, and North Korea)
#     and that User is not otherwise prohibited
# under the Export Laws from receiving the Software.
#
# Copyright 2011 Battelle Memorial Institute.  All Rights Reserved.
# Distributed as open-source under the terms of the Educational Community
# License version 2.0 (ECL 2.0). http://www.opensource.org/licenses/ecl2.php
#
# For further details, see: http://www.globalchange.umd.edu/models/gcam/
#

#Ben/Page's MI parser script
#===========================================================================
# An automated graphing system to process GCAM output data (as generated by the
# ModelInterface) and generate both standard and user-defined graphs.
#
# This file is the main entry point to the backend system.
#
# Original backend module developed by Ben Bond-Lamberty, November 2012
# Modified by GPK, May 2017
# Modified by Rich Plevin, May 2017 to add command-line argument processing

# See https://cran.r-project.org/web/packages/argparser/argparser.pdf
library(argparser, quietly=TRUE)

datestamp <- gsub("-", "_", Sys.Date())

#
# Read defined command-line args and return bindings in a named list.
#
parseArgs <- function() {
  # Create a parser
  p <- arg_parser("Model Interface Template query processor")

  p <- add_argument(p, "--files", nargs=Inf,
                    help="The CSV (query result) files to process")

  p <- add_argument(p, "--logLevel", default=1,
                    help="Set level of diagnostic log messages: 0=None, 1=Errors, 2=Summary, 3=Detail, 4=Debug")

  p <- add_argument(p, "--scriptDir", default=".",
                    help="The directory in which the scripts and mappings directories are found")

  # just an example...
  p <- add_argument(p, '--debug', flag=TRUE, default=FALSE,
                    help="Print diagnostic messages")

  # Parse and return the command line arguments
  argv <- parse_args(p)
  return(argv)
}

args = parseArgs()

loadScripts <- function(names) {
  for (name in names) {
    pathname = file.path(args$scriptDir, "scripts", name)
    source(pathname)
  }
}
# Load all support functions into memory
loadScripts(c("diag_header.R",             # configuration and helper functions
              "diag_parser.R",             # parser to read "ModelInterface" style CSVs
              "diag_grapher.R",            # functions to generate figures
              "color_schemes.R",           # some predefined color schemes
              "diag_util_functions.R",     # useful utility functions
              "GHG_CO2e.R"))               # converter for GHGs to their CO2e values

LOGLEVEL = args$logLevel
#===========================================================================

#Establish constants
#===========================================================================
NDC_OUTPUT_DIR <- "output/"
QUERY_DIR <- "input/queries/"
MAPPING_DIR <- "input/mapping/"
DATA_DIR <- "input/data/"

LINK_FILE_HEADER <- "INPUT_TABLE\nVariable ID\nGHGLink_start\n"

UNAGGREGATED_CONSTRAINTS <- c("USA", "Australia_NZ", "Brazil",
                              "Canada", "China", "EU",
                              "India", "Indonesia", "Japan",
                              "Mexico", "Pakistan", "Russia",
                              "South Africa", "South Korea",
                              "Taiwan", "Argentina", "Colombia")

NDC_START_YEAR <- 2020
NDC_END_YEAR <- 2030
FIRST_PERIOD_AFTER_NDC_END <- 2035

LINK_COLS <- c("region", "linked.ghg.policy", "price.adjust.year", "price.adjust", "demand.adjust.year", "demand.adjust", "market", "linked.policy", "price.unit", "output.unit")
#===========================================================================

#Source scripts, libraries, and create useful functions (NOTE: MARKET for EU-15 is specified in the function)
#===========================================================================
library(dplyr)
library(tidyr)
library(gcamdata)

#Write a csv with a head and tail (eg a csv with a header to run through the modelinterface)
#This is a specific case of the function below made for this script
write_const_csv <- function(x, file, f = write.csv, ...){
  header <- "INPUT_TABLE\nVariable ID\nGHGConstrLong\n"
  tail <- "\nINPUT_TABLE\nVariable ID\nGHGConstrMkt\n\nregion,ghgpolicy,market\nEU-15,GHG,EU"
  # create and open the file connection
  datafile <- file(file, open = 'wt')
  # close on exit
  on.exit(close(datafile))
  # if a header is defined, write it to the file
  writeLines(header,con=datafile)
  # write the file using the defined function and required addition arguments
  f(x, datafile,...)
  # write the tail of the csv
  writeLines(tail, con=datafile)
}

#Write a csv with a head and tail (eg a csv with a header to run through the modelinterface)
write_header_csv <- function(x, file, header, f = write.csv, ...){
  # create and open the file connection
  datafile <- file(file, open = 'wt')
  # close on exit
  on.exit(close(datafile))
  # if a header is defined, write it to the file
  writeLines(header,con=datafile)
  # write the file using the defined function and required addition arguments
  f(x, datafile,...)
}
#===========================================================================

#Read in mappings and important files [QUERY FILE SPECIFIED HERE]
#===========================================================================

INDC_DATA <- read.csv(paste0(DATA_DIR, "INDC_const.csv"), as.is = TRUE)
COPPENHAGEN_DATA <- read.csv(paste0(DATA_DIR, "Coppenhagen_const.csv"), as.is = TRUE)

FILES <- c(paste0(QUERY_DIR, "NDC_QUERY.csv"))

tables <- list()
for( fn in FILES ) {
  tables[[ fn ]] <- parse_mi_output( fn )
}
emissions <- extract_data( "nonCO2 emissions by region") %>% select(-date, -file)
gdp_mer <- extract_data( "GDP MER by region") %>% select(-date, -file)
LU_emissions <- extract_data( "LUC emissions by region") %>% select(-date, -file)

MARKET_MAPPING <- read.csv(paste0(MAPPING_DIR, "market_mapping.csv"), as.is = TRUE)
AR4_DEMAND_ADJUST <- read.csv(paste0(MAPPING_DIR, "AR4_demand_adjust.csv"), as.is = TRUE)
GHG_GROUP_MAPPING <- read.csv(paste0(MAPPING_DIR, "GHG_group_mapping.csv"), as.is = TRUE)
#===========================================================================

#Create the GHG linking file
#===========================================================================
#Certain countries only commited to certain gases or are ignoring LUC emissions
#This approach assumes all countries follow AR4 (though it shouldn't be too difficult to add others given data)
# and all countries within an aggregated region are committed to all ghgs and LUC (assumption)
INDC_DATA %>%
  filter(! rule %in% c("3", "3a")) %>%
  left_join(MARKET_MAPPING, by = c(GCAM_region = "region")) %>%
  select(country, GCAM_region, market, CO2,	CH4,	N2O,	HFCs,	PFCs,	SF6, other_GHG, LULUCF) %>%
  gather(group, accounted, -c(country, GCAM_region, market)) %>%
  mutate(accounted = if_else(is.na(accounted), 0, as.double(accounted)))->
  NDC_link_data

#Individual (or small aggregates such as australia_nz) specifiy which gases and/or LUC emissions to omit
merge(MARKET_MAPPING, AR4_DEMAND_ADJUST) %>%
  left_join(GHG_GROUP_MAPPING, by = "linked.ghg.policy")%>%
  inner_join(NDC_link_data %>% filter(market %in% UNAGGREGATED_CONSTRAINTS), by = c("group", region = "GCAM_region", "market")) %>%
  mutate(demand.adjust.year = if_else(accounted == 1, NDC_START_YEAR, FIRST_PERIOD_AFTER_NDC_END),
         price.adjust.year = if_else(accounted == 1, NDC_START_YEAR, FIRST_PERIOD_AFTER_NDC_END)) %>% #NOTE: This assumes any gas not specifically addressed is not accounted for. Practically (as of 08/07/19) this only affects CF4 and C2F6
  #na.omit() %>%
  select_(.dots = LINK_COLS) %>%
  unique() ->
  individual_linking

#All other regions are assumed to limit all GHGs and LUC emissions
merge(MARKET_MAPPING, AR4_DEMAND_ADJUST) %>%
  filter(!region %in% individual_linking$region) %>%
  mutate(price.adjust.year = 2020,
         demand.adjust.year = 2020) %>%
  bind_rows(individual_linking) %>%
  unique() %>%
  arrange(region) %>%
  select("region", "linked-ghg-policy"="linked.ghg.policy", "price-adjust-year"="price.adjust.year",
         "price-adjust"="price.adjust", "demand-adjust-year" = "demand.adjust.year",
         "demand-adjust"="demand.adjust", "market",
         "linked-policy"="linked.policy", "price-unit"="price.unit", "output-unit"="output.unit") ->
  GHG_linking_file_final

#===========================================================================

#Format emissions and GDP queries
#===========================================================================
emissions %>%
  rename(year = Year) %>%
  filter(region != "Global") %>%
  bind_rows(select(LU_emissions, -LandLeaf) %>% rename(year = Year) %>% mutate(GHG = "CO2_LUC")) %>%
  left_join(GHG_linking_file_final %>% select('region', "linked-ghg-policy", "demand-adjust"), by = c("region", "GHG"="linked-ghg-policy")) %>%
  mutate(value = value * `demand-adjust`) %>%
  filter(!is.na(value)) %>%
  left_join(MARKET_MAPPING, by = "region") %>%
  group_by(scenario, market, year) %>%
  summarise(value = sum(value)) %>%
  ungroup() ->
  BASE_EMISSIONS

if(BASE_EMISSIONS$scenario %>% unique() %>% length() != 1){
  break("Only a reference scenario should be added")
} else BASE_EMISSIONS <- BASE_EMISSIONS %>% select(-scenario)

gdp_mer %>%
  rename(year = Year) %>%
  left_join(MARKET_MAPPING, by = "region") %>%
  group_by(market, year) %>%
  summarise(gdp = sum(value)) ->
  gdp

left_join(BASE_EMISSIONS, gdp, by = c("market", "year")) %>%
  mutate(ghg_intensity = value/gdp)%>%
  select(market, year, ghg_intensity) ->
  ghg_gdp_intensity
#===========================================================================

#Calculate NDCs up to 2030
#===========================================================================
#The basic structure of calculating the NDCs is separated by countries who are aggregated into GCAM regions,
#and countries that are individual GCAM regions already
# NOTE: The EU and Australia_NZ are treated as individual regions rather than aggregated regions

#Strategy for aggregated countries:
# Assume that all regions commited to all GHGs and LUC with AR4
#to simplify aggregating different commitments. Aggregate country level reductions into regions,
#then subtract the reductions from GCAM's BAU.

#Strategy for unaggregated regions:
# Rather than subtract reductions from GCAM's BAU, use each country's commitments as their constraint.


#The rule column separates how different countries calculate their constraints
#   1) a reduction relative to a base year or absolute emissions limit
#   2) a reduction relative to the BAU scenario where the country specified its own BAU
#   3) a reduction where the country did not specify BAU
#   3a) a reduction with no quantifiable values
# Omit rule 3 (and 3a) as we cannot get values to return to GCAM
INDC_DATA %>%
  filter(! rule %in% c("3", "3a")) %>%
  select(country, region = GCAM_region, INDC_UC, INDC_CN, INDC_UC_MtCO2eq, INDC_CN_MtCO2eq, target_year, target_type, ref_point, ref_emiss) %>%
  mutate(INDC_CN = as.double(INDC_CN),
         ref_emiss = as.double(ref_emiss),
         ref_point = if_else(ref_point=="BAU", as.character(target_year), ref_point)) %>%
  left_join(MARKET_MAPPING, by = "region") ->
  NDC_country

#Calculate reductions for aggregated regions
# Note that some countries have committed to an intensity of GDP reduction but this isn't possible to
# calculate in aggregated regions in GCAM as it stands. This calculation will only occur for unaggregated regions
NDC_country %>%
  filter(!market %in% UNAGGREGATED_CONSTRAINTS) %>%
  mutate(units = "MtCO2e",
         reduction_UC =if_else(!is.na(INDC_UC * ref_emiss),
                               INDC_UC * ref_emiss,
                               if_else(!is.na(INDC_UC_MtCO2eq),
                                       if_else(INDC_UC_MtCO2eq<0,
                                               INDC_UC_MtCO2eq,
                                               ref_emiss - INDC_UC_MtCO2eq),
                                       0)),
         reduction_CN = if_else(!is.na(INDC_CN * ref_emiss),
                                INDC_CN * ref_emiss,
                                if_else(!is.na(INDC_CN_MtCO2eq),
                                        if_else(INDC_CN_MtCO2eq<0,
                                                INDC_CN_MtCO2eq,
                                                ref_emiss - INDC_CN_MtCO2eq),
                                        0))) %>%
  group_by(market, target_year, units) %>%
  summarise(reduction_UC = sum(reduction_UC),
            reduction_CN = sum(reduction_CN)) %>%
  ungroup() %>%
  gather(conditional, value, -c("market", "target_year", "units")) %>%
  spread(target_year, value) %>%
  #Goals reached in 2025 need to be added to the goals of 2030 and similarly for 2035
  #NOTE: Several countries give indicative goals, but for a first pass these are ignored
  mutate(`2025` = if_else(is.na(`2025`), 0, `2025`),
         `2030` = if_else(is.na(`2030`), 0, `2030`),
         `2035` = if_else(is.na(`2035`), 0, `2035`),
         `2030` = `2030`+`2025`,
         `2035` = `2030`+`2035`,
         conditional = gsub("reduction", "constraint", conditional)) %>%
  gather(target_year, value, -c("market", "units", "conditional")) %>%
  mutate(target_year = as.integer(target_year)) ->
  aggregate_NDC_reductions

#First account for the Coppenhagen committments
# This is a simple first pass that takes the Copenhagen constraints from the old model and applies them here
# TODO: scale or somehow otherwise alter the coppenhagen committments to match the new emissions pathways
BASE_EMISSIONS %>%
  left_join(COPPENHAGEN_DATA %>% select(market, year, value), by = c("market", "year")) %>%
  mutate(value = if_else(!is.na(value.y)&(value.y<value.x), value.y, value.x)) %>%
  select(market, year, value) ->
  coppenhagen_emissions

#Subtract the reductions from Coppenhagen adjusted GCAM BAU emissions to get GCAM constraints
aggregate_NDC_reductions %>%
  left_join(coppenhagen_emissions %>% rename(base = value), by = c("market" , target_year = "year")) %>%
  mutate(value = value+base) %>%
  select(-base) %>%
  spread(target_year, value) %>%
  left_join(coppenhagen_emissions %>% filter(year == 2020) %>% spread(year, value), by = c("market")) %>%
  mutate(`2025` = if_else((`2030`+`2020`)/2<`2025`, (`2030`+`2020`)/2, `2025`)) %>%
  gather(year, value, -c(market, units, conditional)) %>%
  mutate(year = as.integer(year))->
  aggregate_NDC_R_C_Y

#Calculate constraints for unaggregated regions
# Note that India and China have committed to an intensity of GDP reduction
NDC_country %>%
  filter(market %in% UNAGGREGATED_CONSTRAINTS) %>%
  mutate(units = "MtCO2e",
         constraint_UC =if_else(!is.na((1+INDC_UC) * ref_emiss),
                               (1+INDC_UC) * ref_emiss,
                               if_else(!is.na(INDC_UC_MtCO2eq),
                                       if_else(INDC_UC_MtCO2eq>0 & INDC_UC_MtCO2eq<ref_emiss,
                                               INDC_UC_MtCO2eq,
                                               ref_emiss + INDC_UC_MtCO2eq),
                                       ref_emiss)),
         constraint_CN = if_else(!is.na((1+INDC_CN) * ref_emiss),
                                (1+INDC_CN) * ref_emiss,
                                if_else(!is.na(INDC_CN_MtCO2eq),
                                        if_else(INDC_CN_MtCO2eq>0 & INDC_CN_MtCO2eq<ref_emiss,
                                                INDC_CN_MtCO2eq,
                                                ref_emiss + INDC_CN_MtCO2eq),
                                        ref_emiss))) %>%
  #Because the previous mutate is rather complex the GDP reduction countries
  # will simply overwrite the above constraint.
  left_join(ghg_gdp_intensity %>% mutate(year = as.character(year)), by =c("market", ref_point = "year")) %>%
  left_join(gdp, by =c("market", target_year = "year")) %>%
  mutate(constraint_UC = if_else(target_type == "intensity_GDP",
                                 if_else(!is.na((1+INDC_UC) * ghg_intensity * gdp),
                                         (1+INDC_UC) * ghg_intensity * gdp,
                                         ref_emiss), #Should we default to their ref_emissions their reductions are NA or should we just be unbounded
                                 constraint_UC),
         constraint_CN = if_else(target_type == "intensity_GDP",
                                 if_else(!is.na((1+INDC_CN) * ghg_intensity * gdp),
                                         (1+INDC_CN) * ghg_intensity * gdp,
                                         ref_emiss), #Should we default to their ref_emissions their reductions are NA or should we just be unbounded
                                 constraint_CN)) %>%
  group_by(market, target_year, units) %>%
  summarise(constraint_UC = sum(constraint_UC),
            constraint_CN = sum(constraint_CN)) %>%
  ungroup() %>%
  gather(conditional, value, -c("market", "target_year", "units")) %>%
  spread(target_year, value) ->
  individual_NDC_constraints_R_C

#Most regions target 2030, but the US targets 2025, so treat it seperately
#calculate 2030 by linearly extrapolating the emissions reduction between 2005 and 2025
individual_NDC_constraints_R_C %>%
  filter(is.na(`2030`), market == "USA") %>%
  left_join(coppenhagen_emissions %>% filter(year %in% c(2005, 2020)) %>% spread(year, value), by = "market") %>%
  mutate(`2030` = `2025` + (`2025`- `2005`)/(2025-2005)*(2030-2025)) %>%
  gather(year, value, -c("market", "units", "conditional")) %>%
  mutate(year = as.integer(year)) %>%
  filter(year >= 2020) %>%
  select(market, units, conditional, year, value) ->
  NDC_individual_2025

#Now do regions targeting 2030
individual_NDC_constraints_R_C %>%
  filter(!is.na(`2030`), market != "USA") %>%
  left_join(coppenhagen_emissions %>% filter(year == 2020) %>% spread(year, value), by = "market") %>%
  mutate(`2025` = if_else(is.na(`2025`), (`2030`+`2020`)/2, `2025`)) %>%
  gather(year, value, -c("market", "units", "conditional")) %>%
  mutate(year = as.integer(year)) ->
  NDC_individual_2030

NDC_constraints <- bind_rows(NDC_individual_2025, NDC_individual_2030, aggregate_NDC_R_C_Y)

#Indonesia says that it will be emitting more than GCAM's BAU, so replace any over emissions with baselines
# NDC_constraints %>%
#   left_join(coppenhagen_emissions, by = c("market", "year")) %>%
#   mutate(value = if_else(value.y<value.x, value.y, value.x)) %>%
#   select(names(NDC_constraints)) ->
#   NDC_constraints

BASE_EMISSIONS %>%
  mutate(market = as.character(market)) %>%
  filter(!market %in% unique(pull(NDC_constraints, market))) %>%
  pull(market) %>%
  unique() ->
  uncommitted_regions

#There are 3 regions in GCAM that have no listed NDC commitments.They are added here
# to calculate whatever goal is attempted post 2030, but are filtered out before writing the outputs
BASE_EMISSIONS %>%
  merge(tibble(conditional = c("constraint_CN", "constraint_UC"))) %>%
  filter(!market %in% NDC_constraints$market, year %in% NDC_constraints$year) %>%
  mutate(units = "MtCO2e") %>%
  bind_rows(NDC_constraints) ->
  NDC_constraints
#===========================================================================

#Calculate NDCs for continued ambition, increased ambition, NDC->2deg, and NDC->1.5deg
#===========================================================================
#Different scenarios have different paths for emissions past 2030
#(continued ambition, increased ambition, 2degree scenario, 1.5 degree scenario)
# the first two decarbonize their economy (emissions/$GDP) at the rate they did between 2020 and 2030 (with a minimum of 2% and 5% respectively)
# the latter two decarbonize linearly to 5 MtCO2e in 2070 and 2050 respectively

#Get the ghg_intensity (emissions/unit GDP)
NDC_constraints %>%
  rename(ndc = value) %>%
  left_join(gdp , by = c("market", "year")) %>%
  mutate(ghg_intensity =ndc/gdp, units = "MtCO2e/mil1990$US") %>%
  select(market, conditional, year, ndc, ghg_intensity) ->
  ghg_intens

#Calculate the annual decarbonization rate from the decrease in ghg_intensity
ghg_intens %>%
  select(market, conditional, year, ghg_intensity) %>%
  spread(year, ghg_intensity) %>%
  mutate(ndc_rate = round(1 - (`2030`/`2020`)^(1/10), digits = 2)) %>%
  select(market, conditional, ndc_rate) ->
  decarbonization_rate

#Join together the GDP and decarbonization rate with the ghg intensity to prepare for calculating by scenario
NDC_constraints %>%
  select(market, year, conditional, value) %>%
  group_by(market, year, conditional) %>%
  complete(year = seq(2020, 2100, 5)) %>%
  ungroup() %>%
  left_join(gdp, by = c("market", "year")) %>%
  left_join(decarbonization_rate, by = c("market", "conditional")) %>%
  left_join(ghg_intens %>% filter(year == 2030) %>% select(market, conditional, ghg_intensity), by = c("market", "conditional")) %>%
  left_join(MARKET_MAPPING %>% filter(!duplicated(market)) %>% mutate(ghgpolicy = "GHG"), by = "market")->
  NDC_commitments

#Calculate cont_ambition (minium 2% decarbonization rate)
NDC_commitments %>%
  mutate(ndc_rate = if_else(year >2030 & ndc_rate < .02, .02, ndc_rate ),
         ghg_intensity = ghg_intensity * (1-ndc_rate)^(year-2030),
         value = if_else(year > 2030,
                         if_else(is.na(value),
                                 gdp*ghg_intensity,
                                 if_else(gdp*ghg_intensity<value,
                                         gdp*ghg_intensity,
                                         value)),
                         value)) %>%
  select(region, ghgpolicy, conditional, market, year, value) %>%
  unique() %>%
  #Filter out any region that did not have any NDC commitments
  filter(!(market %in% uncommitted_regions & year <= NDC_END_YEAR))->
  NDC_cont_ambitions

#Calculate cont_ambition (minium 2% decarbonization rate) with Global markets (regions can 'trade' emissions)
NDC_commitments %>%
  mutate(ndc_rate = if_else(year >2030 & ndc_rate < .02, .02, ndc_rate ),
         ghg_intensity = ghg_intensity * (1-ndc_rate)^(year-2030),
         value = if_else(year > 2030,
                         if_else(is.na(value),
                                 gdp*ghg_intensity,
                                 if_else(gdp*ghg_intensity<value,
                                         gdp*ghg_intensity,
                                         value)),
                         value)) %>%
  select(region, ghgpolicy, conditional, market, year, value) %>%
  unique() %>%
  #The region is arbitrary. It could be placed in any region
  mutate(market = "Global", region = "EU-12") %>%
  group_by(region, ghgpolicy, conditional, market, year) %>%
  summarise(value = sum(value)) %>%
  ungroup() ->
  NDC_cont_ambitions_global

#calculate increased ambition (minimum 5% decarbonization rate)
NDC_commitments %>%
  mutate(ndc_rate = if_else(year >2030 & ndc_rate < .05, .05, ndc_rate ),
         ghg_intensity = ghg_intensity * (1-ndc_rate)^(year-2030),
         value = if_else(year > 2030,
                         if_else(is.na(value),
                                 gdp*ghg_intensity,
                                 if_else(gdp*ghg_intensity<value,
                                         gdp*ghg_intensity,
                                         value)),
                         value)) %>%
  select(region, ghgpolicy, conditional, market, year, value) %>%
  unique() %>%
  #Filter out any region that did not have any NDC commitments
  filter(!(market %in% uncommitted_regions & year <= NDC_END_YEAR)) ->
  NDC_incr_ambitions

#calculate NDC to 2 degree pathways
#(note: this is not an exact science and will need to be tweaked with changes in branch or hector)
NDC_commitments %>%
  group_by(market, conditional) %>%
  mutate(value = if_else(year >= 2070,
                         5,
                         value),
         value_test = if_else(!between(year, 2031, 2069), value, as.double(NA)),
         value = approx(year,value,year)$y,
         value_test = approx(year,value_test,year)$y,
         value = if_else(value_test<value, value_test, value)) %>%
  ungroup() %>%
  select(region, ghgpolicy, conditional, market, year, value) %>%
  unique()%>%
  #Filter out any region that did not have any NDC commitments
  filter(!(market %in% uncommitted_regions & year <= NDC_END_YEAR)) ->
  NDC_2_deg

#calculate NDC to 1.5 degree pathways
#(note: this is not an exact science and will need to be tweaked with changes in branch or hector)
NDC_commitments %>%
  group_by(market, conditional) %>%
  mutate(value = if_else(year >= 2050,
                         5,
                         value),
         value_test = if_else(!between(year, 2031, 2049), value, as.double(NA)),
         value = approx(year,value,year)$y,
         value_test = approx(year,value_test,year)$y,
         value = if_else(value_test<value, value_test, value)) %>%
  ungroup() %>%
  select(region, ghgpolicy, conditional, market, year, value) %>%
  unique()%>%
  #Filter out any region that did not have any NDC commitments
  filter(!(market %in% uncommitted_regions & year <= NDC_END_YEAR))->
  NDC_1p5_deg

NDC_cont_ambitions_UC <- filter(NDC_cont_ambitions, conditional == "constraint_UC") %>% select(-conditional)
NDC_cont_ambitions_CN <- filter(NDC_cont_ambitions, conditional == "constraint_CN") %>% select(-conditional)
NDC_cont_ambitions_global_UC <- filter(NDC_cont_ambitions_global, conditional == "constraint_UC") %>% select(-conditional)
NDC_cont_ambitions_global_CN <- filter(NDC_cont_ambitions_global, conditional == "constraint_CN") %>% select(-conditional)
NDC_incr_ambitions_UC <- filter(NDC_incr_ambitions, conditional == "constraint_UC") %>% select(-conditional)
NDC_incr_ambitions_CN <- filter(NDC_incr_ambitions, conditional == "constraint_CN") %>% select(-conditional)
NDC_2_deg_UC <- filter(NDC_2_deg, conditional == "constraint_UC") %>% select(-conditional)
NDC_2_deg_CN <- filter(NDC_2_deg, conditional == "constraint_CN") %>% select(-conditional)
NDC_1p5_deg_UC <- filter(NDC_1p5_deg, conditional == "constraint_UC") %>% select(-conditional)
NDC_1p5_deg_CN <- filter(NDC_1p5_deg, conditional == "constraint_CN") %>% select(-conditional)
#===========================================================================

#Write the outputs as csvs
#===========================================================================
write_const_csv(NDC_cont_ambitions_UC, paste0(NDC_OUTPUT_DIR, "NDC_cont_UC.csv"), row.names = FALSE)
write_const_csv(NDC_cont_ambitions_CN, paste0(NDC_OUTPUT_DIR, "NDC_cont_CN.csv"), row.names = FALSE)
write_const_csv(NDC_incr_ambitions_UC, paste0(NDC_OUTPUT_DIR, "NDC_incr_UC.csv"), row.names = FALSE)
write_const_csv(NDC_incr_ambitions_CN, paste0(NDC_OUTPUT_DIR, "NDC_incr_CN.csv"), row.names = FALSE)
write_const_csv(NDC_2_deg_UC, paste0(NDC_OUTPUT_DIR, "NDC_2deg_UC.csv"), row.names = FALSE)
write_const_csv(NDC_2_deg_CN, paste0(NDC_OUTPUT_DIR, "NDC_2deg_CN.csv"), row.names = FALSE)
write_const_csv(NDC_1p5_deg_UC, paste0(NDC_OUTPUT_DIR, "NDC_1p5deg_UC.csv"), row.names = FALSE)
write_const_csv(NDC_1p5_deg_CN, paste0(NDC_OUTPUT_DIR, "NDC_1p5deg_CN.csv"), row.names = FALSE)
write_header_csv(GHG_linking_file_final, paste0(NDC_OUTPUT_DIR, "GHG_link.csv"), LINK_FILE_HEADER, row.names = FALSE)
#===========================================================================

#Write the outputs as xmls
#===========================================================================
EU.15_market <- data.frame(region = "EU-15", ghgpolicy = "GHG", market = "EU")
global_market <- data.frame(region = MARKET_MAPPING$region[!MARKET_MAPPING$region %in% NDC_cont_ambitions_global$region],
                                ghgpolicy = "GHG",
                                market = "Global")

create_xml(paste0(NDC_OUTPUT_DIR, "NDC_cont_UC.xml")) %>%
  add_xml_data(NDC_cont_ambitions_UC, "GHGConstrLong", NULL) %>%
  add_xml_data(EU.15_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "NDC_cont_CN.xml")) %>%
  add_xml_data(NDC_cont_ambitions_CN, "GHGConstrLong", NULL) %>%
  add_xml_data(EU.15_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "NDC_cont_global_UC.xml")) %>%
  add_xml_data(NDC_cont_ambitions_global_UC, "GHGConstrLong", NULL) %>%
  add_xml_data(global_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "NDC_cont_global_CN.xml")) %>%
  add_xml_data(NDC_cont_ambitions_global_CN, "GHGConstrLong", NULL) %>%
  add_xml_data(global_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "NDC_incr_UC.xml")) %>%
  add_xml_data(NDC_incr_ambitions_UC, "GHGConstrLong", NULL) %>%
  add_xml_data(EU.15_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "NDC_incr_CN.xml")) %>%
  add_xml_data(NDC_incr_ambitions_CN, "GHGConstrLong", NULL) %>%
  add_xml_data(EU.15_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "NDC_2_deg_UC.xml")) %>%
  add_xml_data(NDC_2_deg_UC, "GHGConstrLong", NULL) %>%
  add_xml_data(EU.15_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "NDC_2_deg_CN.xml")) %>%
  add_xml_data(NDC_2_deg_CN, "GHGConstrLong", NULL) %>%
  add_xml_data(EU.15_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "NDC_1p5_deg_UC.xml")) %>%
  add_xml_data(NDC_1p5_deg_UC, "GHGConstrLong", NULL) %>%
  add_xml_data(EU.15_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "NDC_1p5_deg_CN.xml")) %>%
  add_xml_data(NDC_1p5_deg_CN, "GHGConstrLong", NULL) %>%
  add_xml_data(EU.15_market, "GHGConstrMkt", NULL) %>%
  run_xml_conversion()


create_xml(paste0(NDC_OUTPUT_DIR, "GHG_link.xml")) %>%
  add_xml_data(GHG_linking_file_final, "GHGLink_start", NULL) %>%
  run_xml_conversion()
create_xml(paste0(NDC_OUTPUT_DIR, "GHG_link_global.xml")) %>%
  add_xml_data(GHG_linking_file_final %>% mutate(market = "Global"), "GHGLink_start", NULL) %>%
  run_xml_conversion()
#===========================================================================
